### ISSUE TITLE
I am getting this error: "TypeError: proxify is not a function"

### ISSUE THREAD

**Issue by JuanmaMenendez** [tbhaxor/node-proxifyjs#1]
When I just install the dependency and try to run the demo code

```
const proxify = require("node-proxifyjs");
 
(async () => {
  let data = await proxify(); // this will return
  console.log(data);
})();
```

 I am getting this error:

"TypeError: proxify is not a function"

**Comment by tbhaxor** [comment]
With this syntax use

```js
const proxify = require("node-proxifyjs").default;
 
(async () => {
  let data = await proxify(); // this will return
  console.log(data);
})();
```

If issue is resolved, close it

**Comment by tbhaxor** [comment]
Closing this issue. If issue still persists,  feel  free to reopen

**Comment by JuanmaMenendez** [comment]
Thanks for your answer.
After that I got "TypeError: Cannot read property 'count' of undefined"

passing a  `{ count: 20 }` param, fix it and now it is working.

```
(async () => {
  let data = await proxify({ count: 20 }); // this will return
  console.log(data);
})();
```

Please fix the documentation on github and npmjs.com and great project!
